### ISSUE TITLE
Move networking related API configuration to a top level networking key

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#1091]
#### Description

```yaml
networking:
    endpoint: <string>
    local_port: <int>
    api_gateway: public|off
```

Blocked on https://github.com/cortexlabs/cortex/issues/1077

#### TODO

`api_gateway` key should not print for local apis

Fix `UserStr()`; this needs to move and be smarter:

```go
		if api.Networking != nil {
			sb.WriteString(fmt.Sprintf("%s:\n", NetworkingKey))
			sb.WriteString(s.Indent(api.Networking.UserStr(), "  "))
		}
```
