### ISSUE TITLE
support REST API Gateway

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#1197]
### Description

Currently, Cortex supports HTTP API Gateway, but there are some features in REST API Gateways that are not supported by HTTP API Gateways (and are difficult to get around), such as [IAM authentication](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-control-access-using-iam-policies-to-invoke-api.html).

This would add the option for the user to specify whether to use the REST API Gateway or HTTP API Gateway.

### Example config

```yaml
networking:
  api_gateway: none | public  # current
  api_gateway: none | http_public | rest_public | rest_private  # proposal #1
  api_gateway: none | public_http | public_rest | private_rest  # proposal #2
```
