### ISSUE TITLE
offer-features: key "kind" is not supported yet example includes it

### ISSUE THREAD

**Issue by cristianmtr** [cortexlabs/cortex#1214]
#### Version

0.18.1

#### Description

```
error: /home/cristian/code/offers_features/cortex.yaml: offer-features: key "kind" is not supported
```

#### Configuration

```
# cortex.yaml

- name: offer-features
  kind: SyncAPI
  predictor:
    type: python
    path: predictor.py
    config:
      bucket: offer-features-model
      key: model
```

form the iris-classifier example https://github.com/cortexlabs/cortex/blob/master/examples/sklearn/iris-classifier/README.md

I think you need to update the docs
