### ISSUE TITLE
Support environment-dependent variables

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#141]
### Description

Allow the user to specify environment-specific variables that can be used anywhere in the config.

### Motivation

This is necessary to have e.g. dev and prod deployments have a different number of replicas

### Possible config

```yaml
- kind: environment
  name: dev
  ...
  vars:
    replicas: 1
    cpu: "1"
```

```yaml
- kind: api
  ...
  replicas: ${replicas}
  replicas: ${cpu}
```

### Notes

* Are env values all strings? What happens if replacement needs quotes? e.g. `cpu = "1"` vs `executors = 1`. May need custom type which implements YAML unmarshaller which takes the raw string and just passes it through
