### ISSUE TITLE
Support user-defined defaults for all config

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#142]
### Motivation

This would allow the user to specify defaults

### Possible design

```yaml
- kind: RealtimeAPI-defaults
  autoscaling:
    max_replicas: 3
  compute:
    cpu: 1
```
