### ISSUE TITLE
Problems with autoscaling

### ISSUE THREAD

**Issue by dakshvar22** [cortexlabs/cortex#1446]
#### Version

`0.20.0`

#### Description

The number of replicas do not scale with increase in number of in-flight requests. New replicas are requested, but they never come up.

#### Configuration

cortex.yaml

```
- name: ###
  kind: RealtimeAPI
  predictor:
    type: python
    path: predictor.py
    processes_per_replica: 3
    threads_per_process: 1
    image: dakshvar22/cortex_custom:hub
  compute:
    cpu: 1
    gpu: 1 # this is optional, since the api can also run on cpu
    mem: 14G
  autoscaling:  # (aws only)
    min_replicas: 1  # minimum number of replicas (default: 1)
    max_replicas: 3  # maximum number of replicas (default: 100)
    init_replicas: 1  # initial number of replicas (default: <min_replicas>)
    window: 10s
    upscale_stabilization_period: 10s
    max_upscale_factor: 2
  update_strategy:
    max_surge: 0
```

Cluster info produced from `cortex cluster info`

```
fetching cluster status ...

aws access key id:             ****************7ELA
cluster version:               0.20.0
cluster name:                  test
aws region:                    us-east-1
availability zones:            [us-east-1a, us-east-1b]
s3 bucket:                     test-12d2cd140a
instance type:                 g4dn.xlarge
min instances:                 1
max instances:                 3
tags:                          {"cortex.dev/cluster-name": "test"}
instance volume size (Gi):     50
instance volume type:          gp2
instance volume iops:          <null>
use spot instances:            no
cloudwatch log group:          cortex
subnet visibility:             public
nat gateway:                   none
api load balancer scheme:      internet-facing
operator load balancer scheme: internet-facing
api gateway:                   public
telemetry:                     true
operator image:                cortexlabs/operator:0.20.0
manager image:                 cortexlabs/manager:0.20.0
downloader image:              cortexlabs/downloader:0.20.0
request monitor image:         cortexlabs/request-monitor:0.20.0
cluster autoscaler image:      cortexlabs/cluster-autoscaler:0.20.0
metrics server image:          cortexlabs/metrics-server:0.20.0
inferentia image:              cortexlabs/inferentia:0.20.0
neuron rtd image:              cortexlabs/neuron-rtd:0.20.0
nvidia image:                  cortexlabs/nvidia:0.20.0
fluentd image:                 cortexlabs/fluentd:0.20.0
statsd image:                  cortexlabs/statsd:0.20.0
istio proxy image:             cortexlabs/istio-proxy:0.20.0
istio pilot image:             cortexlabs/istio-pilot:0.20.0
istio citadel image:           cortexlabs/istio-citadel:0.20.0
istio galley image:            cortexlabs/istio-galley:0.20.0

your cluster currently costs $0.72 per hour

aws resource                            cost per hour
1 eks cluster                           $0.10
1 instance for your apis                $0.526 total
1 50gb ebs volume for your apis         $0.007 total
1 t3.medium instance for the operator   $0.0416
1 20gb ebs volume for the operator      $0.003
2 network load balancers                $0.045 total

your cluster has 1 API replica running across 1 instance, and 2 unscheduled replicas

instance type   lifecycle   replicas   CPU (requested / total allocatable)   memory (requested / total allocatable)   GPU (requested / total allocatable)
g4dn.xlarge     on-demand   1          1000m / 3190m                         14G / 14893392Ki                         1 / 1
```

I am testing my API with K6 cloud. I am using 10 virtual users each firing a request in one second for a total of 5 minutes. The approx response time for each request should be around 10s which is validated separately by firing just one request. Since the value for `target_replica_concurrency` is unchanged, it should be 3 to start with since i am using 3 processes per replica. Once, the number of concurrent calls goes up the target concurrency I can see that cortex has requested for more replicas, but they never spin up and the number of live instances is always 1 resulting in the very high response times for in-flight requests in the back of the queue.
Am i doing anything wrong?

#### Steps to reproduce

I would expect it to be reproducible with the configurations given above.

#### Expected behavior

Cortex brings up new instances as they are requested.

#### Actual behavior

New instances are requested but they never come up.

#### Stack traces

No errors. `cortex logs <api>` is correctly showing the logs from only one replica.
