### ISSUE TITLE
Number of process started on replica do not match processes_per_replica

### ISSUE THREAD

**Issue by dakshvar22** [cortexlabs/cortex#1448]
#### Version

0.20.0

#### Description

I have set `processes_per_replica` to 5, but when the API goes live on my replica, only three processes are started for it. I particularly request for GPU as the config shows below. Since, i am using g4dn.xlarge instance the total GPU memory available at disposal is 16 GB. Each process should take up 2.2 GB and hence when the 3 processes start I can see that around 7GB is still free to be occupied. The cortex logs also do not indicate any errors because of which processes may not be able to start.

#### Configuration

```
- name: ###
  kind: RealtimeAPI
  predictor:
    type: python
    path: predictor.py
    processes_per_replica: 5
    threads_per_process: 1
    image: dakshvar22/cortex_custom:hub
  compute:
#    cpu: 1
    gpu: 1 # this is optional, since the api can also run on cpu
    mem: 14G
  autoscaling:  # (aws only)
    min_replicas: 1  # minimum number of replicas (default: 1)
    max_replicas: 4  # maximum number of replicas (default: 100)
    init_replicas: 1  # initial number of replicas (default: <min_replicas>)
    window: 10s
    upscale_stabilization_period: 10s
    max_upscale_factor: 2
  update_strategy:
    max_surge: 0
```

#### Steps to reproduce

@deliahu This could be model dependent and hence I may not be able to give a perfect reproducible setup for it. What would be the best way to help debug this?

#### Expected behavior

Number of processes started equal the number of `processes_per_replica`

#### Actual behavior

Number of processes started is always equal to just 3 irrespective of whatever number I set for `processes_per_replica`>=3
