### ISSUE TITLE
Configure log level within the Cortex API spec config

### ISSUE THREAD

**Issue by RobertLucian** [cortexlabs/cortex#1484]
#### Description

Add a field in the `cortex.yaml` API spec that allows the user to set the log level for their API deployments:

```yaml
- name: <string>  # API name (required)
  predictor:
    ...
    log_level: info # allow CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET
    ... 
```

The default log level set would be `INFO`.

Consider adding a guide to showcase using `cx_logger()` in predictor implementations.

#### Motivation

To prevent spamming the log lines with unnecessary information. As pointed out by @vackosar.

#### Issues to sort out

1. Looks like uvicorn ignores our log levels from `log_config.yaml`, and for that, we'd have to have something like:
https://github.com/tiangolo/fastapi/issues/1508#issuecomment-638365277
1. The log levels set in `log_config.yaml` don't seem to apply to the `cx_logger` - `info` is still the default log level regardless of which level is set in `log_config.yaml`.
