### ISSUE TITLE
Make .cortexignore file configurable in the API spec

### ISSUE THREAD

**Issue by RobertLucian** [cortexlabs/cortex#1498]
#### Description

Make `.cortexignore` file configurable:

```yaml
predictor:
  ...
  dependencies:
    ignore: .alternative_cortex_ignore
  ...
```

May have to think about the name selection for the field (or its placement). Can go hand in hand with https://github.com/cortexlabs/cortex/issues/1191.

#### Motivation

In case the user has multiple cortex `cortex.yaml` API configs in the same directory, and for each specific deployment, just a subset of the present files/dependencies has to be present in the deployment. This would also prevent triggering a re-deployment if the files specific to another deployment have changed.
