### ISSUE TITLE
Hard to retrieve logs from cluster > 100 instances

### ISSUE THREAD

**Issue by lapaniku** [cortexlabs/cortex#1538]
#### Version

0.21.0

#### Description

I started experimenting with big clusters of spot instances and from time to time got failed workers in job status. 
```
job id             status                    progress   failed   start time                 duration
69bb1905c592545e   running                   529/1000   17       06 Nov 2020 11:15:29 UTC   12m5s
```

Which is ok, but when I try to get logs it became quite challenging, as I get either:

```
error encountered while fetching logs from cloudwatch: InvalidParameterException: 1 validation error detected: Value '[69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-smpqz_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-txzhz_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-vkbr8_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-x7c2b_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-b92mh_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-nr5fv_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-rfnpb_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-jkk7p_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-zpbvx_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-w2pfx_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-4h6c2_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-m9kbt_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-q4x9z_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-klpgx_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-w8qkr_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-zkpkj_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-b6k8r_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-cx96k_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-gr6j2_api, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-4b96b_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-6hc2b_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-hq5v6_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-s57bk_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-xnlfr_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-6r8lb_api, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-bbfsq_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-hfss2_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-ckdhv_downloader, 69bb50b67e78ddea_imagesearch-batch-69bb50b67e78ddea-ljcdb_downloader, 69bb50b67e78ddea_imagesearch-ba ...' at 'logStreamNames' failed to satisfy constraint: Member must have length less than or equal to 100
```

or 
```
error encountered while searching for log streams: ThrottlingException: Rate exceeded
	status code: 400, request id: adc71b03-a1c5-4091-8402-52cc006efeff
```

It's clear that retrieving logs for such an amount of workers is challenging, that's why I wonder if it has some workaround. Or what is the best way to discover issues with some workers in such cases.

*Note*: I created a tiny instance to run cortex commands (create cluster and deploy) in the same region and account to reduce any network issues.

#### Configuration

```
cluster_name: cortex

# AWS region
region: us-east-1

# instance type
instance_type: t3.small

min_instances: 1
max_instances: 1000

# whether to use spot instances in the cluster; spot instances are not guaranteed to be available so please take that into account for production clusters (default: false)
spot: true

spot_config:
  on_demand_base_capacity: 0
  on_demand_percentage_above_base_capacity: 0
  on_demand_backup: true
```
#### Steps to reproduce

1. Start a cluster with more than 100 spot instances
2. Start a job with the same amount of workers as spot instances (> 100) 
3. Try to fetch the corresponding job logs

#### Expected behavior

Got some actual logs

#### Actual behavior

Errors described above

#### Suggested solution

It might make sense to filter out logs somehow and show only errors if possible, as now I get `pip install ...` requirements logs which are not quite useful.
