### ISSUE TITLE
Local models not available when running cortex get for the TF predictor and when live-reloading is enabled

### ISSUE THREAD

**Issue by RobertLucian** [cortexlabs/cortex#1554]
#### Version

0.22

#### Description

When using a TensorFlow predictor and when live-reloading is enabled, local models that were passed in using the API spec, don't show up when running `cortex get <api-name>`.

```yaml
- name: api
   kind: RealtimeAPI
   predictor:
     type: python
     model_path: ~/local-model/resnet50/
     ...
```

#### Consequence

No local model is accessible for inference.
