### ISSUE TITLE
Add support for QueueAPI kind to pull from SQS

### ISSUE THREAD

**Issue by RobertLucian** [cortexlabs/cortex#1586]
#### Description

Instead of making requests directly to a real-time API or by submitting jobs to an API, one alternative is to specify an SQS queue to an API and then let the API pull the objects from the queue as they come in. Scaling is done based on the number of objects pulled from the queue.

An API spec could look like this:
```yaml
name: <api-name>
kind: QueueAPI
predictor:
  type: python # can also be onnx or tensorflow
  path: predictor.py
  queue: <queue-name>
```

The `predictor.py` layout would still be the same and the `payload` parameter would be set to whatever it's pulled from the SQS queue.

#### Motivation

An alternative to RealtimeAPI/BatchAPI. Also requested by @Greg-Tarr.

#### Notes

* May be related to https://github.com/cortexlabs/cortex/issues/1610
