### ISSUE TITLE
submitted the job request with "workers: 20" but only 5 spot instances are running

### ISSUE THREAD

**Issue by nellaG** [cortexlabs/cortex#1593]
#### Version

0.22.1

#### Description
hello,
when I'm submitting the job request with `workers` value above 5, only 5 spot instances are running and remaining quantity of requested workers are in pending status. (e.g. when `workers` is 20, only 5 workers are running and 15 workers are pending)

I checked AWS EC2 spot worker autoscaling group via AWS console, when the job is submitted, the `desired capacity` is set to 5. (not 20)
#### Configuration

```
cortex.yaml
- name: 
  kind: BatchAPI
  predictor:
    type: python
    path: predictor.py
    image: cortexlabs/python-predictor-gpu:0.22.1
    env:
      ENV: aws
  compute:
    mem: 2G
    gpu: 1
```

```
cluster.yaml
instance_type: g4dn.xlarge
min_instances: 0
max_instances: 200
instance_volume_size: 30
instance_volume_type: gp2
spot: true
spot_config:
    instance_distribution: [g4dn.xlarge]
    on_demand_base_capacity: 1
    on_demand_percentage_above_base_capacity: 0
    on_demand_backup: true # recommended for production clusters
```
```
$ cortex cluster info
aws region:                                    ap-northeast-2
availability zones:                            [ap-northeast-2a, ap-northeast-2c]
instance type:                                 g4dn.xlarge
min instances:                                 0
max instances:                                200
use spot instances:                            yes
spot instance distribution:                    [g4dn.xlarge]
spot on demand base capacity:                  1
spot on demand percentage above base capacity: 0
spot instance pools:                           1
on demand backup:                              yes
```

#### Steps to reproduce

1. configure `max_instances` above 5
2. submit the job with `workers` above 5
3. get the job info with `cortex get {api_name} {job_id}`

#### Expected behavior

all of requested workers are should be `running`  concurrently

#### Actual behavior

only 5 workers are in running and remaining is `pending`

#### Screenshots

(optional)

#### Stack traces

(error output from `cortex logs <api name>`)

```text
<paste stack traces here>
```

#### Additional context

(optional)

#### Suggested solution

(optional)
