### ISSUE TITLE
Support environment variables in yaml configuration

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#1609]
for example:

```yaml
- kind: RealtimeAPI
  autoscaling:
    max_replicas: ${replicas}
  compute:
    cpu: ${cpu}
```
