### ISSUE TITLE
cortex job is terminated before executing api cause it cannot find SQS queue

### ISSUE THREAD

**Issue by nellaG** [cortexlabs/cortex#1648]
### Version

0.22.1

### Description

Submitted cortex job but it is intermittently terminated because the cortex operator cannot find SQS queue.

The cortex operator's log looks like:
```
{
    "log": "terminating job 69b377c15a1314be (example-api api); sqs queue with url https://sqs.ap-northeast-2.amazonaws.com/{key}/9867795cbb-example-api-69b377c15a1314be.fifo was not found"
}
```
The same job id's api logging and downloader logging is not triggered.

### Configuration

cortex.yaml
```
- name: 
  kind: BatchAPI
  predictor:
    type: python
    path: predictor.py
    image: cortexlabs/python-predictor-gpu:0.22.1
    env:
      DEVICE: '0'
      ENV: aws
      SQS_REGION: ap-northeast-2
  compute:
    mem: 2G
    gpu: 1
```

cluster.yaml
```
region: ap-northeast-2
instance_type: g4dn.xlarge
min_instances: 0
max_instances: 250
instance_volume_size: 30
instance_volume_type: gp2
subnet_visibility: public
nat_gateway: none
api_load_balancer_scheme: internet-facing
operator_load_balancer_scheme: internet-facing
spot: true

spot_config:
    instance_distribution: [g4dn.xlarge]
    on_demand_base_capacity: 1
    on_demand_percentage_above_base_capacity: 0
    on_demand_backup: true
```
### Steps to reproduce

1. submit the job
2. intermittently the job is failed

### Expected behavior

(describe the behavior you expected)

### Actual behavior

(describe the behavior you experienced)

### Screenshots

(optional)

### Stack traces

```text
cortex logs example-api 69b377c15a1314be       
using aws environment
terminating job 69b377c15a1314be (example-api api); sqs queue with url https://sqs.ap-northeast-2.amazonaws.com/{key}/9867795cbb-example-api-69b377c15a1314be.fifo was not found
```

### Additional context

(optional)

### Suggested solution

(optional)
