### ISSUE TITLE
[local] predictor.type: python programe just use one core

### ISSUE THREAD

**Issue by JanYunkai** [cortexlabs/cortex#1727]
cortex.yaml
``` 
- name: product1
  kind: RealtimeAPI
  predictor:
    type: python
    path: predictor.py
  compute:
    cpu: 3
  networking:
    api_gateway: public
```
predictor.py

```
class PythonPredictor:

    def __init__(self, config):
        from tensorflow.keras.models import load_model
        from tensorflow.keras import backend as K

        model = load_model('xx.h5')
        self.model_func = K.function(inputs=[model.input], outputs=[model.output])

    def predict(self, payload, query_params, headers):
        idx_list = []
        val_list = []
        result = []
        for item in payload:
            a_list = [-1] * 4835
            compress_vals = item['data'].items()
            for (key,val) in compress_vals:
                a_list[int(key)] = val

            idx_list.append((item["idx"], item["date"]))
            val_list.append(np.array(a_list))
        
        val_matrix = np.array(val_list)
        score = self.model_func([val_matrix])
        for (idx, date), s in zip(idx_list, zip(*score)):
            result.append({"idx": idx, "score": str(list(s[0])), "date": date})

        return result
```

cortex deploy

**how can i use the full 3 core?**

export model by flask i can config as follows
```
import multiprocessing
workers = multiprocessing.cpu_count()
worker_class="gevent"
....
```

**Comment by deliahu** [comment]
@JanYunkai You can configure Cortex to use multiple workers with the `processes_per_replica` field.

Here are all of the [configuration options](https://docs.cortex.dev/workloads/realtime/configuration#python-predictor), and in your case, it might work like this:

```yaml
- name: product1
  kind: RealtimeAPI
  predictor:
    type: python
    path: predictor.py
    processes_per_replica: 6
  compute:
    cpu: 3
  networking:
    api_gateway: public
```
