### ISSUE TITLE
Allow ELB to select instance based on model loaded in memory

### ISSUE THREAD

**Issue by lminer** [cortexlabs/cortex#1873]
It would be nice if, when receiving a request, the ELB tried to route the request to a server that already has a model in memory.

I'm currently using a multi-model predictor with six separate models. There is a 10 second cost to load a model into memory. Even though I have 6 servers running simultaneously, I always incur the 10 second expense, because the ELB doesn't know that it should favor the instance that already has the requested model loaded in memory.

**Comment by RobertLucian** [comment]
Are you using the multi-model caching functionality?

**Comment by lminer** [comment]
Yeah. If I request the same model repeatedly, I don't see the 10 second switching cost.

**Comment by lminer** [comment]
Here's my `cortex.yaml`

```
- name: foo
  kind: RealtimeAPI
  predictor:
    type: tensorflow
    path: foo/cortex_server.py
    models:
      paths:
        - foo
      cache_size: 1
      disk_cache_size: 6
    processes_per_replica: 1
    threads_per_process: 1
    image: quay.io/cortexlabs/tensorflow-predictor:0.27.0
    tensorflow_serving_image: quay.io/cortexlabs/tensorflow-serving-gpu:0.27.0
  compute:
    gpu: 1
  autoscaling:
    min_replicas: 6
    max_replicas: 6
```
