### ISSUE TITLE
Error (image pull)

### ISSUE THREAD

**Issue by wise-east** [cortexlabs/cortex#1990]
### Version

cli version: 0.25.0
cluster version: 0.25.0

### Description

Deployed APIs were working fine until yesterday, but they went down with the status `error (image pull)`.  
Even after doing `cortex deploy cortex.yaml` or `cortex refresh <api name>`, it still has the same status after showing `updating` for some time. I can't get any logs with `cortex logs <api name>`. 

### Configuration

```
- name: dialogpt-alexa
  kind: RealtimeAPI
  predictor:
    type: python
    path: predictor.py
    config:
      bucket: viola-models
      model_dir: dialogpt_alexa/
      files:
        model: GP2-pretrain-step-832.pkl
        model_config: config.json
        vocab: vocab.json
        merges: merges.txt
  compute:
    cpu: 1
    gpu: 1
```

### Expected behavior

status to be brought back to `live`

### Actual behavior

status stays at `error (image pull)`

### Screenshots

<img width="673" alt="Screen Shot 2021-03-22 at 4 43 09 PM" src="https://user-images.githubusercontent.com/31977186/112071747-b1efbd00-8b2d-11eb-9ed1-733786804b0c.png">

### Additional context

In case it helps, here's my `cluster.yaml`
```
# cluster.yaml

# EKS cluster name for cortex (default: cortex)
cluster_name: viola-cortex

# AWS region
region: us-east-1

# S3 bucket (default: <cluster_name>-<RANDOM_ID>)
bucket: viola-models

# List of availability zones for your region (default: 3 random availability zones from the specified region)
availability_zones:  [us-east-1a, us-east-1b, us-east-1c]

# instance type
# instance_type: p2.xlarge
instance_type: g4dn.xlarge

# minimum number of instances (must be >= 0)
min_instances: 2

# maximum number of instances (must be >= 1)
max_instances: 16

# instance volume size (GB) (default: 50)
instance_volume_size: 20


# whether to use spot instances in the cluster (default: false)
# see https://cortex.dev/v/0.15/cluster-management/spot-instances for additional details on spot configuration
spot: true

spot_config:
    instance_distribution: [g4dn.2xlarge, g3s.xlarge, g3.4xlarge, g4dn.4xlarge]
    on_demand_backup: true

```

**Comment by vishalbollu** [comment]
There is a quay.io outage https://status.quay.io/ that is the source of the problem here. Cortex uses quay.io to host and deliver images. Because of the outage, your cluster is unable to pull images. Any provisioning of new replicas/workers will be impacted (cortex cluster* commands , cortex deploy and autoscaling).

To get around the quay outage and become more resilient to outages in the future, you can configure your cortex cluster and your APIs to pull images from a registry of your choice. This will involve spinning up a new cluster and redeploying your APIs with the image fields set to your images from your registry.

Unfortunately because quay.io is down, it isn't possible to export images from Cortex's quay registry to your own registry. You will have to build images from directly from the Cortex repo.

Here are some high level instructions that may help (I have not run through all of the scenarios to verify if they work as expected).

It can take 60 to 90 minutes to build and push all of the images. It is recommended to do this on an ec2 instance in the same region as your ECR to speed up the build and push time.

1. Clone the Cortex repository and check in to the tag that matches cortex version exactly `git checkout v0.25.0`.
1. Export your AWS credentials
```bash
export AWS_ACCESS_KEY_ID=""
export AWS_SECRET_ACCESS_KEY=""
export AWS_ACCOUNT_ID="***"
export AWS_REGION="us-west-2"
```

For cortex <= 0.23
1. `make registry-create`
1. `make images-all`

For cortex >= 0.24
1. `make registry-create-aws`
1. `make images-all-aws`

The path for the image will take on the form: `<AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/cortexlabs/operator:<CORTEX_VERSION>`

Once you've built all of the images:
* Navigate to your cortex version's cluster installation docs to find the complete list of images used by the cluster. Set all of these values to point to your new registry. That should look something like this (the complete images may change based on your cortex version):
```yaml
# cluster.yaml
...
image_operator: <account_id>.dkr.ecr.<region>.amazonaws.com/cortexlabs/operator:<CORTEX_VERSION>
image_manager: <account_id>.dkr.ecr.<region>.amazonaws.com/cortexlabs/manager:<CORTEX_VERSION>
image_downloader: <account_id>.dkr.ecr.<region>.amazonaws.com/cortexlabs/downloader:<CORTEX_VERSION>
image_request_monitor: <account_id>.dkr.ecr.<region>.amazonaws.com/cortexlabs/request-monitor:<CORTEX_VERSION>
image_cluster_autoscaler: <account_id>.dkr.ecr.<region>.amazonaws.com/cortexlabs/cluster-autoscaler:<CORTEX_VERSION>
image_metrics_server: <account_id>.dkr.ecr.<region>.amazonaws.com/cortexlabs/metrics-server:<CORTEX_VERSION>
image_inferentia: <account_id>.dkr.ecr.<region>.amazonaws.com/cortexlabs/inferentia:<CORTEX_VERSION>
image_neuron_rtd: <account_id>.dkr.ecr.<region>.amazonaws.com/cortexlabs/neuron-rtd:<CORTEX_VERSION>
image_nvidia: <account_id>.dkr.ecr.<region>.amazonaws.com/cortexlabs/nvidia:<CORTEX_VERSION>
image_fluentd: <account_id>.dkr.ecr.<region>.amazonaws.com/cortexlabs/fluentd:<CORTEX_VERSION>
image_statsd: <account_id>.dkr.ecr.<region>.amazonaws.com/cortexlabs/statsd:<CORTEX_VERSION>
image_istio_proxy: <account_id>.dkr.ecr.<region>.amazonaws.com/cortexlabs/istio-proxy:<CORTEX_VERSION>
image_istio_pilot: <account_id>.dkr.ecr.<region>.amazonaws.com/cortexlabs/istio-pilot:<CORTEX_VERSION>
```
* Navigate to your cortex version's api specs to find the relevant image fields you need to set for your API specs and update the `cortex.yaml` accordingly.

Spin up the new cluster pointing to your new images and verify that your API deployments are working as expected.
