### ISSUE TITLE
Tags missing in nodegroups added using `cortex cluster configure` command

### ISSUE THREAD

**Issue by dipen-epi** [cortexlabs/cortex#2392]
### Version
`0.40`

### Description
Nodegroups added after initial deployment of cluster do not contain the tags defined in `cluster.yaml` config file using the `cortex cluster configure` command. Not facing the same issue with `cortex cluster up` command

### Configuration

```yaml
cluster_name: cortex-models-dev
image_manager: xxx.dkr.ecr.us-east-1.amazonaws.com/cortex-custom:0.40
region: us-east-1
node_groups:
- name: test-ng-cpu-L2s
  instance_type: c5.2xlarge
  min_instances: 0
  max_instances: 25
  priority: 100
  spot: true
  spot_config:
    instance_distribution:
    - c5.2xlarge
    - c5.4xlarge
    on_demand_base_capacity: 0
    on_demand_percentage_above_base_capacity: 0
- name: test-ng-cpu-L2
  instance_type: c5.2xlarge
  min_instances: 0
  max_instances: 25
  priority: 90
  spot: false
  spot_config: null
tags:
  CortexVersion: 0.40.0
  Cost_Center_Name: xxx
  Team: xxx
  cortex.dev/cluster-name: cortex-models-dev
availability_zones: []
iam_policy_arns:
- arn:aws:iam::xxx:policy/cortex-default-policy-dev
subnet_visibility: private
subnets:
- availability_zone: us-east-1a
  subnet_id: subnet-aaa
- availability_zone: us-east-1b
  subnet_id: subnet-bbb
- availability_zone: us-east-1d
  subnet_id: subnet-ccc
nat_gateway: none
ssl_certificate_arn: arn:aws:acm:us-east-1:xxx:certificate/xxx
api_load_balancer_scheme: internal
operator_load_balancer_scheme: internal
api_load_balancer_cidr_white_list:
- 0.0.0.0/0
operator_load_balancer_cidr_white_list:
- 0.0.0.0/0
vpc_cidr: x.x.x.x/16
telemetry: true
```
### Steps to reproduce

1. `cortex cluster up` with nodegroup A containing example tags
2. Once cortex is deployed, add another nodegroup B to the same `cluster.yaml` (not modifying tags)
3. Modify with `cortex cluster configure`

### Expected behavior
Tags should be applied to nodegroups added with `cortex cluster configure`

### Actual behavior
Tags not applied

### Stack traces

Not relevant

### Additional context

(optional)

### Suggested solution

(optional)
