### ISSUE TITLE
Custom predict path for Async API

### ISSUE THREAD

**Issue by imshashank** [cortexlabs/cortex#2434]
Is there a way to change the "default" path "/" to add a prefix like "/predict" for AsyncAPI?

```
- name: text-generator
  kind: AsyncAPI
  pod:
    port: 8080
    - http:
        paths:
        - path: /predict
          pathType: Prefix
    containers:
    - name: api
      image: quay.io/cortexlabs-test/async-text-generator-cpu:latest
      compute:
        cpu: 1
        mem: 2.5Gi
```
