### ISSUE TITLE
Make CORS headers configurable

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#541]
### Description

Option 1:

```yaml
kind: api
name: my-api
...
enable_cors: true
```

Option 2:

```yaml
kind: api
name: my-api
...
cors:
    Access-Control-Allow-Origin: <string>
    Access-Control-Allow-Headers: <string>
```
