### ISSUE TITLE
Allow predictor base images to be overridden in API configuration

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#900]
#### Motivation

* Different APIs may benefit from having different base images
* Allow rolling updates when updating the base image

#### Design

Add a top-level key under predictor `image`
```
- name: iris-classifier
   predictor:
    type: python
    path: predictor.py
    image: ecr/dockerhub link
```

* `image` defaults to cortex default images if user doesn't specify key
* validate that the image path, check access to image (prioritize DockerHub, we may be able to add ECR later)
