### ISSUE TITLE
Support custom containers in APIs

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#930]
#### Description

Support the ability to add custom containers to API pods. The predictor client would contain information on how to connect to the inference container.

#### Motivation

This could be used as a custom model inference server (e.g. for users who already have custom serving containers or who want to use unsupported runtimes like Java/Scala), to handle pre-processing steps, or anything else.

#### Proposed API

```yaml
predictor:
  type: python|tensorflow|onnx

  ...
  
  containers:
  - image: <string>  # docker image to use for the custom container (required)
    init_script: <string>  # path to a bash or python file which runs before starting the model server (e.g. to download files) (optional)
    entrypoint: [string]  # container entrypoint (optional)
    args: [string]  # container args (optional)
    working_dir: <string>  # container working directory (optional)
    liveness_probe:  # k8s liveness probe
      handler:
        type: exec|http|tcp
        command: [string]  # (exec only) the command line to execute inside the container (required)
        path: <string>  # (http only) path to access on the server (optional)
        port: <int>  # (http or tcp only) port to access on the server (required)
        host: <string>  # (http or tcp only) host name to connect to, defaults to the pod IP (optional)
        scheme: <string>  # (http only) scheme for connecting to the host (default: http)
        headers: <string>  # (http only) custom headers to set in the request (optional)
      initial_delay_seconds: <int>  # number of seconds after the container has started before probe is initialized
      timeout_seconds: <int>  # number of seconds after which the probe times out
      period_seconds: <int>  # how often (in seconds) to perform the probe
      success_threshold: <int>  # minimum consecutive successes for the probe to be considered successful after having failed
      failure_threshold: <int>  # minimum consecutive failures for the probe to be considered failed after having succeeded
    readiness_probe: <probe>  # k8s readiness probe
    startup_probe: <probe>  # k8s startup probe
```
