### ISSUE TITLE
Use environment.yml to install packages in Dockerfiles

### ISSUE THREAD

**Issue by RobertLucian** [cortexlabs/cortex#938]
#### Description

Create the base environment and install the python packages in one go by using an `environment.yml` config file. For now, this is not advised, because the dev machines don't have enough RAM memory. Once the machines are upgraded, this will possible. Related PR here https://github.com/cortexlabs/cortex/pull/880. 

```yaml
name: env
channels:
    - defaults
    - conda-forge
dependencies:
    - conda-forge::python=3.6.9
    - pip
    - pip:
        - --install-option="--no-cache-dir"
        - -r file:lib/requirements.txt
        - -r file:serve/requirements.txt
```

#### Motivation

When working with conda environments, it's best to install everything (conda packages & pip packages) in one go to prevent the environment from entering a broken state. The likelihood of the environment to break gets higher the more commands are run one after the another.
